"""Add birthday and qualification to employee

Revision ID: ca30fa6d1999
Revises: c1353eb0cf0d
Create Date: 2026-02-26 22:13:09.678380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca30fa6d1999'
down_revision: Union[str, Sequence[str], None] = 'c1353eb0cf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('qualification', sa.String(), nullable=True))
    op.alter_column('employees', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'TERMINATED', 'ON_LEAVE', 'PROSPECTIVE', name='employmentstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'TERMINATED', 'ON_LEAVE', 'PROSPECTIVE', name='employmentstatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('employees', 'qualification')
    op.drop_column('employees', 'date_of_birth')
    # ### end Alembic commands ###
